"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createQuote,createQuoteCategory,createTask,deleteQuote,deleteTask,getDecisions,getProfiles,getQuoteCategories,getQuotes,getTasks,requestPasswordReset,saveDecision,Session,setPassword,signIn,signedDocumentUrl,updateTaskStatus,uploadDocument} from "../lib/supabase-rest";
type Profile={id:string;full_name:string;role:string};
type LineItem={description:string;details:string|null;amount_excl_vat:number};
type Category={id:string;name:string};
type Quote={id:string;number:string;supplier_name:string|null;company_name:string;description:string|null;amount:number;amount_excl_vat:number|null;line_items:LineItem[];category_id:string|null;status:"concept"|"verzonden"|"akkoord"|"afgewezen";owner_id:string;document_path:string|null;original_filename:string|null;decision_note:string|null;created_at:string;due_at:string|null};
type Decision={id:string;quote_id:string;user_id:string;choice:"akkoord"|"overleg"|"afwijzen";comment:string|null;updated_at:string};
type Task={id:string;title:string;status:"ja"|"nee"|"bezig";owner_id:string;updated_by:string|null;updated_at:string;created_at:string};
const euro=new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR",maximumFractionDigits:0});
const statusLabel={concept:"Te beoordelen",verzonden:"In behandeling",akkoord:"Goedgekeurd",afgewezen:"Afgewezen"};

type ExtractedQuote={supplier:string;amountExcl:string;amountIncl:string;project:string;description:string;lineItems:LineItem[]};
function cleanPdfText(value:string){return value.replace(/\s+/g," ").trim()}
function parseDutchAmount(value:string){const normalized=value.replace(/[^\d,.-]/g,"").replace(/\.(?=\d{3}(?:\D|$))/g,"").replace(",",".");const amount=Number(normalized);return Number.isFinite(amount)?amount:0}
async function recognizePdfLocally(file:File):Promise<ExtractedQuote>{
 const pdfUrl="https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs";
 const pdfjs=await import(/* @vite-ignore */ pdfUrl) as {GlobalWorkerOptions:{workerSrc:string};getDocument:(options:{data:ArrayBuffer})=>{promise:Promise<{numPages:number;getPage:(page:number)=>Promise<{getTextContent:()=>Promise<{items:Array<{str?:string;hasEOL?:boolean}>}>}>}>}};
 pdfjs.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs";
 const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;const lines:string[]=[];
 for(let page=1;page<=Math.min(pdf.numPages,8);page++){const content=await (await pdf.getPage(page)).getTextContent();let line="";for(const item of content.items){line+=`${item.str||""} `;if(item.hasEOL&&cleanPdfText(line)){lines.push(cleanPdfText(line));line=""}}if(cleanPdfText(line))lines.push(cleanPdfText(line))}
 const text=lines.join("\n");if(text.length<30)throw new Error("Deze PDF bevat geen leesbare tekst. Gebruik een duidelijke PDF of afbeelding.");
 const exclMatch=text.match(/(?:totaal|subtotaal|offertebedrag)[^\n]{0,35}(?:excl(?:usief)?\.?\s*btw)[^\n€]{0,25}(?:€|eur)?\s*([\d.]+,\d{2})|(?:totaal|subtotaal|offertebedrag)[^\n€]{0,25}(?:€|eur)?\s*([\d.]+,\d{2})[^\n]{0,25}(?:excl(?:usief)?\.?\s*btw)/i);const inclMatch=text.match(/(?:totaal|te betalen|offertebedrag)[^\n]{0,35}(?:incl(?:usief)?\.?\s*btw)[^\n€]{0,25}(?:€|eur)?\s*([\d.]+,\d{2})|(?:totaal|te betalen|offertebedrag)[^\n€]{0,25}(?:€|eur)?\s*([\d.]+,\d{2})[^\n]{0,25}(?:incl(?:usief)?\.?\s*btw)/i);const labeledAmount=text.match(/(?:totaal(?:bedrag)?|offertebedrag|te betalen)[^\n€]{0,45}(?:€|eur)?\s*([\d.]+,\d{2})/i);const allAmounts=[...text.matchAll(/(?:€|eur)\s*([\d.]+(?:,\d{2})?)/gi)].map(m=>parseDutchAmount(m[1])).filter(n=>n>0);const amountExcl=parseDutchAmount(exclMatch?.[1]||exclMatch?.[2]||"");const amountIncl=parseDutchAmount(inclMatch?.[1]||inclMatch?.[2]||"")||(labeledAmount?parseDutchAmount(labeledAmount[1]):Math.max(0,...allAmounts));
 const supplierLabel=lines.find(l=>/^(?:leverancier|offerte van|afzender)\s*:/i.test(l));const companyLine=lines.slice(0,35).find(l=>/\b(?:b\.?v\.?|n\.?v\.?|v\.?o\.?f\.?|holding|nederland)\b/i.test(l)&&!/klant|opdrachtgever|factuuradres/i.test(l));const supplier=cleanPdfText((supplierLabel?.split(":").slice(1).join(":")||companyLine||lines.find(l=>/[a-z]{3,}/i.test(l))||"").slice(0,100));
 const lineItems:LineItem[]=[];for(const line of lines){if(/totaal|subtotaal|btw|te betalen/i.test(line))continue;const match=line.match(/^(.{3,}?)\s+(?:€|eur)?\s*([\d.]+,\d{2})\s*$/i);if(!match)continue;const label=cleanPdfText(match[1]);const parts=label.split(/\s{2,}|\s[-–—]\s/).filter(Boolean);lineItems.push({description:(parts[0]||label).slice(0,100),details:parts.slice(1).join(" · ").slice(0,180)||null,amount_excl_vat:parseDutchAmount(match[2])})}
 const projectLine=lines.find(l=>/^(?:betreft|onderwerp|project|omschrijving|werkzaamheden)\s*:/i.test(l));const fallbackProject=file.name.replace(/\.[^.]+$/,"").replace(/^offerte[_ -]*/i,"").replace(/[_-]+/g," ");const project=cleanPdfText((projectLine?.split(":").slice(1).join(":")||fallbackProject).slice(0,120));
 return {supplier,amountExcl:amountExcl?String(amountExcl):"",amountIncl:amountIncl?String(amountIncl):"",project,description:project?`Ontvangen offerte voor ${project}.`:"Ontvangen offerte.",lineItems:lineItems.slice(0,20)};
}
function recognizeTextLines(lines:string[],file:File):ExtractedQuote{
 const text=lines.map(cleanPdfText).filter(Boolean).join("\n");if(text.length<20)throw new Error("Het bestand bevat te weinig leesbare tekst.");
 const money=(pattern:RegExp)=>{const match=text.match(pattern);return parseDutchAmount(match?.[1]||match?.[2]||"")};
 const amountExcl=money(/(?:totaal|subtotaal|offertebedrag)[^\n]{0,40}(?:excl(?:usief)?\.?\s*btw)[^\n€]{0,25}(?:€|eur)?\s*([\d.]+,\d{2})|(?:totaal|subtotaal)[^\n€]{0,25}(?:€|eur)?\s*([\d.]+,\d{2})[^\n]{0,25}excl/i);
 const amountIncl=money(/(?:totaal|te betalen|offertebedrag)[^\n]{0,40}(?:incl(?:usief)?\.?\s*btw)[^\n€]{0,25}(?:€|eur)?\s*([\d.]+,\d{2})|(?:totaal|te betalen)[^\n€]{0,25}(?:€|eur)?\s*([\d.]+,\d{2})[^\n]{0,25}incl/i);
 const supplierLabel=lines.find(l=>/^(?:leverancier|offerte van|afzender)\s*:/i.test(l));const company=lines.slice(0,30).find(l=>/\b(?:b\.?v\.?|n\.?v\.?|v\.?o\.?f\.?|holding|nederland)\b/i.test(l)&&!/klant|opdrachtgever/i.test(l));const supplier=cleanPdfText(supplierLabel?.split(":").slice(1).join(":")||company||lines[0]||"").slice(0,100);
 const projectLine=lines.find(l=>/^(?:betreft|onderwerp|project|omschrijving)\s*:/i.test(l));const project=cleanPdfText(projectLine?.split(":").slice(1).join(":")||file.name.replace(/\.[^.]+$/,"").replace(/^offerte[_ -]*/i,"").replace(/[_-]+/g," ")).slice(0,120);
 const lineItems:LineItem[]=[];for(const raw of lines){const line=cleanPdfText(raw);if(/totaal|subtotaal|btw|te betalen/i.test(line))continue;const match=line.match(/^(.{3,}?)\s+(?:€|eur)?\s*([\d.]+,\d{2})\s*$/i);if(match)lineItems.push({description:cleanPdfText(match[1]).slice(0,100),details:null,amount_excl_vat:parseDutchAmount(match[2])})}
 const fallbackIncl=amountIncl||Math.max(0,...[...text.matchAll(/(?:€|eur)\s*([\d.]+,\d{2})/gi)].map(m=>parseDutchAmount(m[1])));
 return {supplier,amountExcl:amountExcl?String(amountExcl):"",amountIncl:fallbackIncl?String(fallbackIncl):"",project,description:`Ontvangen offerte voor ${project}.`,lineItems:lineItems.slice(0,20)};
}
async function recognizeDocumentLocally(file:File):Promise<ExtractedQuote>{
 if(file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf"))return recognizePdfLocally(file);
 if(file.type==="text/plain"||file.name.toLowerCase().endsWith(".txt"))return recognizeTextLines((await file.text()).split(/\r?\n/),file);
 if(file.name.toLowerCase().endsWith(".docx")){const zipUrl="https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm";const module=await import(/* @vite-ignore */ zipUrl) as {default:new()=>{loadAsync:(data:ArrayBuffer)=>Promise<{file:(name:string)=>{async:(type:string)=>Promise<string>}|null}>}};const zip=await new module.default().loadAsync(await file.arrayBuffer());const document=zip.file("word/document.xml");if(!document)throw new Error("Het Word-bestand bevat geen leesbare documenttekst.");const xml=await document.async("string");const parsed=new DOMParser().parseFromString(xml,"application/xml");const paragraphs=[...parsed.getElementsByTagName("w:p")].map(p=>[...p.getElementsByTagName("w:t")].map(t=>t.textContent||"").join(" "));return recognizeTextLines(paragraphs,file)}
 throw new Error("Dit bestandstype kan niet automatisch worden gelezen.");
}

export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[recoveryToken,setRecoveryToken]=useState(""),[resetDone,setResetDone]=useState(false),[resetSent,setResetSent]=useState(false),[profiles,setProfiles]=useState<Profile[]>([]),[quotes,setQuotes]=useState<Quote[]>([]),[categories,setCategories]=useState<Category[]>([]),[decisions,setDecisions]=useState<Decision[]>([]),[tasks,setTasks]=useState<Task[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[upload,setUpload]=useState(false),[passwordOpen,setPasswordOpen]=useState(false),[passwordMessage,setPasswordMessage]=useState(""),[selected,setSelected]=useState<Quote|null>(null),[query,setQuery]=useState(""),[filter,setFilter]=useState("alles"),[categoryFilter,setCategoryFilter]=useState("alles");
 const [extracting,setExtracting]=useState(false),[extractError,setExtractError]=useState(""),[supplier,setSupplier]=useState(""),[amountExcl,setAmountExcl]=useState(""),[amount,setAmount]=useState(""),[project,setProject]=useState(""),[description,setDescription]=useState(""),[lineItems,setLineItems]=useState<LineItem[]>([]);
 useEffect(()=>{const hash=new URLSearchParams(window.location.hash.slice(1));if(hash.get("type")==="recovery"&&hash.get("access_token")){setRecoveryToken(hash.get("access_token")!);setLoading(false);return}const raw=localStorage.getItem("atelier-session");if(raw)setSession(JSON.parse(raw));else setLoading(false)},[]);
 const refresh=useCallback(async()=>{if(!session)return;try{const [p,q,c,d,t]=await Promise.all([getProfiles(session.access_token),getQuotes(session.access_token),getQuoteCategories(session.access_token),getDecisions(session.access_token),getTasks(session.access_token)]);setProfiles(p);setQuotes(q);setCategories(c);setDecisions(d);setTasks(t);setError("")}catch(e){setError(e instanceof Error?e.message:"Laden mislukt")}finally{setLoading(false)}},[session]);
 useEffect(()=>{refresh();const t=setInterval(refresh,10000);return()=>clearInterval(t)},[refresh]);
 const me=profiles.find(p=>p.id===session?.user.id); const name=(id:string)=>profiles.find(p=>p.id===id)?.full_name||"Niet toegewezen";const myDecision=(quoteId:string)=>decisions.find(d=>d.quote_id===quoteId&&d.user_id===session?.user.id);
 const shown=useMemo(()=>quotes.filter(q=>(filter==="alles"||q.status===filter)&&(categoryFilter==="alles"||q.category_id===categoryFilter)&&`${q.supplier_name} ${q.company_name} ${q.number}`.toLowerCase().includes(query.toLowerCase())),[quotes,filter,categoryFilter,query]);
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const d=new FormData(e.currentTarget);try{const s=await signIn(String(d.get("email")),String(d.get("password")));localStorage.setItem("atelier-session",JSON.stringify(s));setSession(s)}catch(e){setError(e instanceof Error?e.message:"Inloggen mislukt");setLoading(false)}}
 async function resetPassword(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),password=String(d.get("password")),confirm=String(d.get("confirm"));if(password.length<8){setError("Gebruik minimaal 8 tekens.");return}if(password!==confirm){setError("De wachtwoorden zijn niet hetzelfde.");return}setLoading(true);setError("");try{await setPassword(recoveryToken,password);window.history.replaceState({},"",window.location.pathname);setRecoveryToken("");setResetDone(true)}catch(e){setError(e instanceof Error?e.message:"Instellen mislukt")}finally{setLoading(false)}}
 async function sendReset(){setLoading(true);setError("");try{await requestPasswordReset("elbay.e@hotmail.com",`${window.location.origin}/`);setResetSent(true)}catch(e){setError(e instanceof Error?e.message:"Versturen mislukt")}finally{setLoading(false)}}
 function logout(){localStorage.removeItem("atelier-session");setSession(null);setProfiles([]);setQuotes([])}
 async function changePassword(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!session)return;const form=e.currentTarget,data=new FormData(form),password=String(data.get("password")),confirm=String(data.get("confirm"));setPasswordMessage("");if(password.length<8){setPasswordMessage("Gebruik minimaal 8 tekens.");return}if(password!==confirm){setPasswordMessage("De wachtwoorden zijn niet hetzelfde.");return}setLoading(true);try{await setPassword(session.access_token,password);form.reset();setPasswordMessage("Wachtwoord succesvol gewijzigd.")}catch(e){setPasswordMessage(e instanceof Error?e.message:"Wachtwoord wijzigen is niet gelukt.")}finally{setLoading(false)}}
 function openUpload(){setSupplier("");setAmountExcl("");setAmount("");setProject("");setDescription("");setLineItems([]);setExtractError("");setError("");setUpload(true)}
 async function recognize(file:File){if(!file.size)return;setExtracting(true);setExtractError("");try{const data=new FormData();data.append("file",file);const response=await fetch("/api/extract-quote",{method:"POST",body:data});const result=await response.json();if(!response.ok)throw new Error(result.error||"Online herkenning niet bereikbaar");setSupplier(result.supplier||"");setAmountExcl(result.amount_excl_vat==null?"":String(result.amount_excl_vat));setAmount(result.amount_incl_vat==null?"":String(result.amount_incl_vat));setProject(result.project||"");setDescription(result.description||"");setLineItems(Array.isArray(result.line_items)?result.line_items:[])}catch{try{const result=await recognizeDocumentLocally(file);setSupplier(result.supplier);setAmountExcl(result.amountExcl);setAmount(result.amountIncl);setProject(result.project);setDescription(result.description);setLineItems(result.lineItems);setExtractError(result.supplier&&result.project?"":"Niet alle gegevens konden worden gevonden. Controleer en vul de lege velden aan.")}catch(e){setExtractError(e instanceof Error?e.message:"Automatisch herkennen is niet bereikbaar. Vul de gegevens voorlopig zelf in.")}}finally{setExtracting(false)}}
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!session)return;setLoading(true);const d=new FormData(e.currentTarget),file=d.get("file") as File;try{const path=await uploadDocument(session.access_token,session.user.id,file);await createQuote(session.access_token,{number:`ONT-${new Date().getFullYear()}-${String(quotes.length+1).padStart(3,"0")}`,supplier_name:String(d.get("supplier")),company_name:String(d.get("project")),description:String(d.get("description")),amount:Number(d.get("amount")),amount_excl_vat:d.get("amount_excl")?Number(d.get("amount_excl")):null,line_items:lineItems,category_id:String(d.get("category")),status:"concept",owner_id:String(d.get("owner")),created_by:session.user.id,document_path:path,original_filename:file.name,mime_type:file.type,due_at:d.get("due")||null});setUpload(false);await refresh()}catch(e){setError(e instanceof Error?e.message:"Upload mislukt")}finally{setLoading(false)}}
 async function addCategory(){if(!session)return;const name=window.prompt("Naam van de nieuwe categorie:");if(!name?.trim())return;try{const category=await createQuoteCategory(session.access_token,session.user.id,name);setCategories(current=>[...current,category].sort((a,b)=>a.name.localeCompare(b.name,"nl")));return category.id}catch(e){setError(e instanceof Error?e.message:"Categorie toevoegen mislukt")}}
 async function addTaskItem(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!session)return;const form=e.currentTarget,data=new FormData(form),title=String(data.get("title")).trim();if(!title)return;setLoading(true);try{await createTask(session.access_token,{title,owner_id:session.user.id,created_by:session.user.id,status:"bezig",updated_by:session.user.id,updated_at:new Date().toISOString()});form.reset();await refresh()}catch(e){setError(e instanceof Error?e.message:"Taak toevoegen mislukt")}finally{setLoading(false)}}
 async function changeTaskStatus(task:Task,status:Task["status"]){if(!session)return;setLoading(true);try{await updateTaskStatus(session.access_token,task.id,{status,owner_id:session.user.id,updated_by:session.user.id,updated_at:new Date().toISOString(),completed_at:status==="ja"?new Date().toISOString():null});await refresh()}catch(e){setError(e instanceof Error?e.message:"Taak wijzigen mislukt")}finally{setLoading(false)}}
 async function removeTaskItem(task:Task){if(!session||!window.confirm(`Taak “${task.title}” verwijderen?`))return;setLoading(true);try{await deleteTask(session.access_token,task.id);await refresh()}catch(e){setError(e instanceof Error?e.message:"Taak verwijderen mislukt")}finally{setLoading(false)}}
 async function remove(q:Quote){if(!session||!window.confirm(`Offerte van ${q.supplier_name||"deze leverancier"} definitief verwijderen?`))return;setLoading(true);try{await deleteQuote(session.access_token,q.id,q.document_path);setSelected(null);await refresh()}catch(e){setError(e instanceof Error?e.message:"Verwijderen mislukt")}finally{setLoading(false)}}
 async function decide(choice:Decision["choice"],comment:string){if(!session||!selected)return;setLoading(true);try{await saveDecision(session.access_token,{quote_id:selected.id,user_id:session.user.id,choice,comment:comment||null,updated_at:new Date().toISOString()});await refresh()}catch(e){setError(e instanceof Error?e.message:"Opslaan mislukt")}finally{setLoading(false)}}
 async function openDoc(q:Quote){if(!session||!q.document_path)return;try{window.open(await signedDocumentUrl(session.access_token,q.document_path),"_blank","noopener,noreferrer")}catch(e){setError(e instanceof Error?e.message:"Openen mislukt")}}
 if(recoveryToken)return <main className="login-page"><section className="login-card"><div className="brand login-brand"><span className="brand-mark">O</span><span>Offertekamer</span></div><span className="eyebrow">VEILIG ACCOUNT</span><h1>Nieuw wachtwoord</h1><p>Kies een nieuw wachtwoord van minimaal 8 tekens.</p><form onSubmit={resetPassword}><label>Nieuw wachtwoord<input name="password" type="password" minLength={8} required autoFocus/></label><label>Herhaal wachtwoord<input name="confirm" type="password" minLength={8} required/></label>{error&&<div className="form-error">{error}</div>}<button className="primary" disabled={loading}>{loading?"Opslaan…":"Wachtwoord instellen"}</button></form></section></main>;
 if(!session)return <main className="login-page"><section className="login-card"><div className="brand login-brand"><span className="brand-mark">O</span><span>Offertekamer</span></div><span className="eyebrow">SAMEN BESLISSEN</span><h1>{resetDone?"Wachtwoord ingesteld":"Welkom terug"}</h1><p>{resetDone?"Je kunt nu inloggen met je nieuwe wachtwoord.":"Log in om ontvangen offertes te bekijken, vergelijken en beoordelen."}</p><form onSubmit={login}><label>E-mailadres<input name="email" type="email" defaultValue="elbay.e@hotmail.com" required/></label><label>Wachtwoord<input name="password" type="password" required/></label>{error&&<div className="form-error">{error}</div>}<button className="primary" disabled={loading}>{loading?"Even wachten…":"Inloggen"}</button><button type="button" className="forgot-button" onClick={sendReset} disabled={loading}>{resetSent?"Herstelmail verstuurd ✓":"Wachtwoord vergeten?"}</button></form></section></main>;
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">O</span><span>Offertekamer</span></div><nav><a className="active" href="#"><span>⌂</span>Overzicht</a><a href="#offertes"><span>▤</span>Ontvangen offertes<b>{quotes.length}</b></a><a href="#besluiten"><span>✓</span>Besluiten</a><a href="#taken"><span>☑</span>Taken<b>{tasks.length}</b></a></nav><div className="team-block"><small>TEAM</small>{profiles.map((p,i)=><div className="team-person" key={p.id}><span className={`avatar ${["coral","blue","purple"][i%3]}`}>{p.full_name.slice(0,2).toUpperCase()}</span><span><strong>{p.full_name}</strong><em>{p.role==="admin"?"Beheerder":"Gebruiker"}</em></span><i className="online"/></div>)}</div><div className="sidebar-bottom"><button className="password-button" onClick={()=>{setPasswordMessage("");setPasswordOpen(true)}}>⌘ Wachtwoord wijzigen</button><div className="profile"><span className="avatar dark">{(me?.full_name||"U").slice(0,2).toUpperCase()}</span><span><strong>{me?.full_name||session.user.email}</strong><em>{me?.role==="admin"?"Beheerder":"Gebruiker"}</em></span><button onClick={logout} title="Uitloggen">↪</button></div></div></aside>
 <section className="content"><header><div><span className="eyebrow">GEZAMENLIJK OVERZICHT</span><h1>Ontvangen offertes</h1><p>Bekijk documenten, wijs een eigenaar toe en leg samen een besluit vast.</p></div><button className="primary" onClick={openUpload}>↑ Offerte uploaden</button></header>
  {error&&<div className="banner-error">{error}<button onClick={()=>setError("")}>×</button></div>}
  <div className="stats"><article><div><span>Te beoordelen</span><strong>{quotes.filter(q=>q.status==="concept").length}</strong><small>Wachten op een besluit</small></div><div className="stat-icon sand">?</div></article><article><div><span>In behandeling</span><strong>{quotes.filter(q=>q.status==="verzonden").length}</strong><small>Heeft een verantwoordelijke</small></div><div className="stat-icon peach">↗</div></article><article><div><span>Goedgekeurd</span><strong>{quotes.filter(q=>q.status==="akkoord").length}</strong><small>Besluit vastgelegd</small></div><div className="stat-icon mint">✓</div></article><article><div><span>Totale waarde excl. btw</span><strong>{euro.format(quotes.reduce((s,q)=>s+Number(q.amount_excl_vat||0),0))}</strong><small>Alle ontvangen offertes</small></div><div className="stat-icon violet">€</div></article><article><div><span>Totale waarde incl. btw</span><strong>{euro.format(quotes.reduce((s,q)=>s+Number(q.amount||0),0))}</strong><small>Alle ontvangen offertes</small></div><div className="stat-icon mint">€</div></article></div>
  <section className="category-overview"><div className="category-heading"><div><h2>Categorieën</h2><p>Offertes en totale waarden per groep</p></div><button className="secondary" onClick={addCategory}>+ Nieuwe categorie</button></div><div className="category-cards">{categories.map(category=>{const items=quotes.filter(q=>q.category_id===category.id);return <button key={category.id} className={categoryFilter===category.id?"category-card active":"category-card"} onClick={()=>setCategoryFilter(categoryFilter===category.id?"alles":category.id)}><span><strong>{category.name}</strong><small>{items.length} offerte{items.length===1?"":"s"}</small></span><span><small>Excl. btw</small><b>{euro.format(items.reduce((sum,q)=>sum+Number(q.amount_excl_vat||0),0))}</b></span><span><small>Incl. btw</small><b>{euro.format(items.reduce((sum,q)=>sum+Number(q.amount||0),0))}</b></span></button>})}</div></section>
  <section className="panel" id="offertes"><div className="panel-title"><div><h2>{categoryFilter==="alles"?"Alle documenten":`Categorie: ${categories.find(c=>c.id===categoryFilter)?.name||""}`}</h2><p>Wordt iedere 10 seconden bijgewerkt</p></div><button onClick={refresh} className="refresh">↻ Vernieuwen</button></div><div className="filters"><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Zoek op leverancier, project of nummer…"/></label><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="alles">Alle categorieën</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="alles">Alle statussen</option><option value="concept">Te beoordelen</option><option value="verzonden">In behandeling</option><option value="akkoord">Goedgekeurd</option><option value="afgewezen">Afgewezen</option></select></div>
   <div className="quote-grid">{shown.map(q=><article className={myDecision(q.id)?"quote-card reviewed":"quote-card"} key={q.id}><div className="document-icon">PDF</div><div className="quote-main"><div className="quote-top"><span className={`status ${q.status}`}>{statusLabel[q.status]}</span>{myDecision(q.id)&&<span className={`my-decision ${myDecision(q.id)?.choice}`}>✓ Door jou beoordeeld: {myDecision(q.id)?.choice}</span>}<small>{q.number}</small></div><h3>{q.supplier_name||"Onbekende leverancier"}</h3><p>{q.company_name}{q.description?` · ${q.description}`:""}</p>{q.line_items?.length>0&&<div className="line-items"><div className="line-items-head"><strong>Omschrijving</strong><strong>Bedrag excl. btw</strong></div>{q.line_items.slice(0,5).map((item,index)=><div className="line-item" key={`${q.id}-${index}`}><span><strong>{item.description}</strong>{item.details&&<small>{item.details}</small>}</span><b>{euro.format(item.amount_excl_vat)}</b></div>)}{q.line_items.length>5&&<small className="more-items">+ {q.line_items.length-5} andere posten in de offerte</small>}</div>}<div className="quote-info"><span><small>Excl. btw</small><strong>{q.amount_excl_vat==null?"—":euro.format(q.amount_excl_vat)}</strong></span><span><small>Incl. btw</small><strong>{euro.format(q.amount)}</strong></span><span><small>Eigenaar</small><strong>{name(q.owner_id)}</strong></span><span><small>Ontvangen</small><strong>{new Date(q.created_at).toLocaleDateString("nl-NL")}</strong></span></div><div className="quote-actions"><button className="secondary" onClick={()=>openDoc(q)}>Document openen</button><button className={myDecision(q.id)?"reviewed-button":"primary"} onClick={()=>setSelected(q)}>{myDecision(q.id)?"Beoordeling wijzigen":"Beoordelen"}</button></div></div></article>)}{!shown.length&&<div className="empty-state"><strong>Nog geen offertes</strong><p>Upload de eerste ontvangen offerte om samen te beoordelen.</p><button className="primary" onClick={openUpload}>Offerte uploaden</button></div>}</div></section>
  <section className="panel tasks-panel" id="taken"><div className="panel-title"><div><h2>Checklist</h2><p>Vink een taak af zodra deze klaar is</p></div><span className="check-progress">{tasks.filter(t=>t.status==="ja").length} van {tasks.length} klaar</span></div><form className="task-add" onSubmit={addTaskItem}><input name="title" placeholder="Bijv. Vergunning aanvragen" required/><button className="primary" disabled={loading}>+ Taak toevoegen</button></form><div className="shared-tasks">{tasks.map(task=><article className={task.status==="ja"?"shared-task completed":"shared-task"} key={task.id}><button className="check-button" aria-label={task.status==="ja"?"Taak opnieuw openen":"Taak afvinken"} onClick={()=>changeTaskStatus(task,task.status==="ja"?"bezig":"ja")}>{task.status==="ja"?"✓":""}</button><div className="task-copy"><strong>{task.title}</strong><small>{task.status==="ja"&&task.updated_by?`Afgevinkt door ${name(task.updated_by)} · ${new Date(task.updated_at).toLocaleString("nl-NL",{dateStyle:"short",timeStyle:"short"})}`:`Openstaande taak · toegevoegd door ${name(task.owner_id)}`}</small></div><button className="task-delete" onClick={()=>removeTaskItem(task)} title="Taak verwijderen">×</button></article>)}{!tasks.length&&<div className="empty"><strong>Nog geen taken</strong><p>Voeg hierboven de eerste taak aan de checklist toe.</p></div>}</div></section>
 </section>
 {passwordOpen&&<div className="modal-backdrop"><section className="modal password-modal"><div className="modal-head"><div><span className="eyebrow">VEILIG ACCOUNT</span><h2>Wachtwoord wijzigen</h2><p>Kies een nieuw wachtwoord van minimaal acht tekens.</p></div><button onClick={()=>setPasswordOpen(false)}>×</button></div><form onSubmit={changePassword}><label>Nieuw wachtwoord<input name="password" type="password" minLength={8} autoComplete="new-password" required autoFocus/></label><label>Herhaal nieuw wachtwoord<input name="confirm" type="password" minLength={8} autoComplete="new-password" required/></label>{passwordMessage&&<div className={passwordMessage.includes("succesvol")?"password-success":"form-error"}>{passwordMessage}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setPasswordOpen(false)}>Annuleren</button><button className="primary" disabled={loading}>{loading?"Opslaan…":"Wachtwoord opslaan"}</button></div></form></section></div>}
 {upload&&<div className="modal-backdrop"><section className="modal upload-modal"><div className="modal-head"><div><span className="eyebrow">NIEUW DOCUMENT</span><h2>Ontvangen offerte uploaden</h2><p>PDF, afbeelding, Word (.docx) of tekstbestand (.txt), maximaal 10 MB.</p></div><button onClick={()=>setUpload(false)}>×</button></div><form onSubmit={add}><div className="upload-fields"><label>Offertebestand<input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.docx,.txt,application/pdf,image/jpeg,image/png,image/webp,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" onChange={e=>{const file=e.target.files?.[0];if(file)recognize(file)}} required/></label>{extracting&&<div className="recognition-status"><span className="recognition-spinner"/>Offerte wordt gelezen en ingevuld…</div>}{extractError&&<div className="recognition-error"><strong>Niet alle gegevens zijn automatisch herkend.</strong><span>{extractError}</span><small>Controleer de bedragen hieronder en vul ontbrekende gegevens aan.</small></div>}<label>Leverancier<input name="supplier" value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="Wordt automatisch herkend" required/></label><div className="form-row"><label>Bedrag excl. btw (€)<input name="amount_excl" value={amountExcl} onChange={e=>setAmountExcl(e.target.value)} type="number" min="0" step="0.01" placeholder="Exclusief btw"/></label><label>Bedrag incl. btw (€)<input name="amount" value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0" step="0.01" placeholder="Inclusief btw" required/></label></div><label>Project of onderwerp<input name="project" value={project} onChange={e=>setProject(e.target.value)} placeholder="Wordt automatisch herkend" required/></label><label>Korte toelichting<textarea name="description" value={description} onChange={e=>setDescription(e.target.value)} rows={3} placeholder="Wordt automatisch herkend"/></label><small className="recognition-help">Controleer de herkende gegevens; je kunt alles nog aanpassen.</small><div className="category-picker"><label>Categorie<select name="category" defaultValue={categories.find(c=>c.name.toLowerCase()==="equipment")?.id||categories[0]?.id} required>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><button type="button" className="secondary" onClick={addCategory}>+ Nieuwe categorie</button></div><div className="form-row"><label>Verantwoordelijke<select name="owner" required>{profiles.map(p=><option value={p.id} key={p.id}>{p.full_name}</option>)}</select></label><label>Beslissen vóór<input name="due" type="date"/></label></div></div><div className="modal-actions upload-actions"><button type="button" className="secondary" onClick={()=>setUpload(false)}>Annuleren</button><button className="primary" disabled={loading||extracting}>{extracting?"Offerte lezen…":loading?"Uploaden…":"Gereed: uploaden en delen"}</button></div></form></section></div>}
 {selected&&<DecisionView quote={selected} decisions={decisions.filter(d=>d.quote_id===selected.id)} profiles={profiles} currentUser={session.user.id} onClose={()=>setSelected(null)} onOpen={()=>openDoc(selected)} onDelete={()=>remove(selected)} onDecide={decide}/>}</main>}

function DecisionView({quote,decisions,profiles,currentUser,onClose,onOpen,onDelete,onDecide}:{quote:Quote;decisions:Decision[];profiles:Profile[];currentUser:string;onClose:()=>void;onOpen:()=>void;onDelete:()=>void;onDecide:(s:Decision["choice"],n:string)=>void}){const mine=decisions.find(d=>d.user_id===currentUser);const [note,setNote]=useState(mine?.comment||"");const person=(id:string)=>profiles.find(p=>p.id===id)?.full_name||"Gebruiker";return <div className="modal-backdrop detail-backdrop"><section className="modal decision-modal"><div className="modal-head"><div><span className="eyebrow">ONTVANGEN OFFERTE</span><p>{quote.supplier_name}</p><h2>{quote.company_name}</h2></div><div className="amount-block"><small>{quote.amount_excl_vat!=null?`${euro.format(quote.amount_excl_vat)} excl. btw`:"Excl. btw onbekend"}</small><strong>{euro.format(quote.amount)}</strong><span className="status concept">In beoordeling</span></div><button onClick={onClose}>×</button></div><div className="decision-body"><button className="document-preview" onClick={onOpen}><span>PDF</span><span><strong>{quote.original_filename}</strong><small>Ontvangen {new Date(quote.created_at).toLocaleDateString("nl-NL")} · toegevoegd door {person(quote.owner_id)}</small></span><em>Bekijken</em></button>{quote.description&&<div className="quote-note"><strong>Notitie</strong><p>{quote.description}</p></div>}<section className="vote-section"><h3>Jouw beslissing</h3><p>Iedere gebruiker ziet direct de actuele keuze.</p><div className="vote-buttons"><button className={mine?.choice==="akkoord"?"chosen approve":""} onClick={()=>onDecide("akkoord",note)}>✓ Akkoord</button><button className={mine?.choice==="overleg"?"chosen ask":""} onClick={()=>onDecide("overleg",note)}>？ Overleg</button><button className={mine?.choice==="afwijzen"?"chosen reject":""} onClick={()=>onDecide("afwijzen",note)}>× Afwijzen</button></div><label>Jouw toelichting<textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} placeholder="Schrijf kort waarom je hiervoor kiest…"/></label><div className="team-decisions">{decisions.map(d=><article key={d.id}><span className={`avatar mini ${d.choice==="akkoord"?"blue":d.choice==="afwijzen"?"coral":"purple"}`}>{person(d.user_id).slice(0,2).toUpperCase()}</span><div><strong>{person(d.user_id)} <em>{d.choice}</em></strong><p>{d.comment||"Geen toelichting toegevoegd."}</p></div></article>)}{!decisions.length&&<p className="no-decisions">Nog niemand heeft een keuze gemaakt.</p>}</div><button className="delete-quote" onClick={onDelete}>Offerte verwijderen</button></section></div></section></div>}

